### PR TITLE
Replace Texture Arrays with Individual Textures

### PR DESCRIPTION
**Pull request by moosichu**
DO NOT MERGE, IN DEVELOPMENT AND NOT CURRENTLY FUNCTIONING

Creating this PR now so we can evaluate the scope of the changes and analyse the tradeoffs that this change is making.

Problems this could solve.

✔️ #291 - Switch doesn't support texture arrays properly (NOTE: Unity have said they are aware of this bug and are working on a fix)
✔️ #279, #301 (MAYBE), not sure about this, but the change could be relevant to these issues (and at least allow us to test potentially causes for them).
✔️ Allow for the independent ping-ponging of simulations at different lods (eg. for the dynamic sim where we might want a different number of steps at each scale).

Problems potentially introduced.
❌ Some code complexity increase: can make things harder to maintain, as each simulation needs to keep track of more state. (Also, we will have to set material properties per-lod again, which also presents CPU overhead)
❌ Sampling in data from across cascades #315 - we will need to carefully think about how to tackle problems like these going forward
❌ Remove the potential for further optimizations and decreases in complexity which we have yet to take advantage of.
❌ All multi-lod single-dispatch shaders will no longer be possible. Increasing CPU overhead (we need to properly profile the costs here).

This change aims to mitigate the above issues by restricting this change *only* to textures and keeping the existing naming semantics.  The reason for this is that we may want to move back to using texture arrays, especially if the mentioned bugs all get squashed by Unity (could we reach-out to them about some of them?).

Once this PR is in a working state, I will also have a look and see how we could potentially factor code so that we can limit the changes that need to be made - abstracting TA behavior such that this can be achieved.

### CODE REVIEW

**Comment by moosichu** [comment]
Every TODO is marked with `TODO(SRT):`

**Comment by huwb** [comment]
Thanks dude, great summary. Couple of small clarifications that i didnt understand while reading:

Reduce the need for some branching in the shader to handle sampling out of TA bounds <- is this still a thing? i think we're solving this problem by duplicating the data for the last cascade, but maybe i'm missing/forgetting some branches in some shaders?

Some code complexity decrease <- could you please cite which ones? not trying to nitpick, just to build a clear picture.

**Comment by moosichu** [comment]
You are right on the former, and on the latter I think that was just referring to the branching, so that can go as well.

**Comment by dizzy2003** [comment]
Is there any ETA on this branch working, we have a switch build to deliver at the end of the month and will have to take a stab at this ourselves soon. 

If we do it, any pointers on how you would like it done would be good, so we can hand our changes back. I agree abstracting out the texturearrays would be the best solution

**Comment by moosichu** [comment]
Hi @dizzy2003,

We are currently trying a different approach now because Crest does now have some behaviour now which would break without TAs. However, until the Switch version of Unity is patched to better support texture arrays, you are more than welcome to try this branch out. It isn't "clean" but should be serviceable enough for a demo.

Animated Waves and Depth work in this branch, but I haven't done so for the other LodData, if you could let me know which of the others you use I can focus on getting them working. However, this would be as a temporary fix for the upcoming build you have to deliver, we have another solution in the works that should fix the issues people have been having on their PCs whilst keeping texture arrays. Would that work for you in the long term once Unity has been fixed?

**Comment by dizzy2003** [comment]
> Hi @dizzy2003,
> 
> We are currently trying a different approach now because Crest does now have some behaviour now which would break without TAs. However, until the Switch version of Unity is patched to better support texture arrays, you are more than welcome to try this branch out. It isn't "clean" but should be serviceable enough for a demo.
> 
> Animated Waves and Depth work in this branch, but I haven't done so for the other LodData, if you could let me know which of the others you use I can focus on getting them working. However, this would be as a temporary fix for the upcoming build you have to deliver, we have another solution in the works that should fix the issues people have been having on their PCs whilst keeping texture arrays. Would that work for you in the long term once Unity has been fixed?

Hi Moosichu, we use foam and dynamics, a temp fix would be fine if something better is on the horizon.  Will give this branch a test as is, and see how it runs on switch.

**Comment by huwb** [comment]
Closing. this was a super useful exercise and great to have on record, but i guess we're going to stick with TAs. If that changes lets reopen.

**Comment by huwb** [comment]
Oh just read the last comments @dizzy2003 , sorry these fell by the wayside. i'm not sure this PR is a good place to track them, should we create an issue if they're still occuring?

its worth noting we're hoping to replace the way collision is done, as in #344 . this may impact the bug you mention.

**Pull request closed without merging**
