### PR TITLE
Wizard for placing water bodies

### PR DESCRIPTION
**Pull request by huwb**
Part of #361 

Window for creating local bodies of water.

This is similar to what is in #361, except i gave the window a state (idle vs placing) so that it doesnt always show the translation gizmo, and i removed the proxy object option as it only shows when in placement mode.

I also moved some gerstner validation which was firing a warning while gerstner waves were being created.

### CODE REVIEW

**Comment by moosichu** [comment]
Sweet! Will have a look eitehr later this afternoon or tomorrow. :)

**Comment by huwb** [comment]
Thanks.

What do you mean by other primitives?

**Comment by daleeidd** [comment]
Meshes. Like spheres and capsules.

**Comment by huwb** [comment]
Ah gotcha.

I think i'd be looking for 2d primitives - quads, circles, etc. The primitive will probably feed the sea level as well so wants to be flat. Not sure if using 3d primitives still makes sense.

**Pull request merged**
