### PR TITLE
Initiliase chunks for ocean mask even if it's disabled in the scene hiearchy

### PR DESCRIPTION
**Pull request by moosichu**
This ensures that for when we disable chunk rendering in the scene
hiearchy for things like local water bodies or other optimisations, if
they will still be correclty renderered as part of the ocean mask which
assumes that chunks will always form a continous surface for the post
process effect to work accurately.

### CODE REVIEW

**Comment by moosichu** [comment]
image

Previously with this setup, you would have gaps in the mask resulting in areas with no post-process effect being applied. This circumvents that issue:

image

**Comment by huwb** [comment]
Thanks dude. Was naively hoping this wasnt required after i seemed to get good results just stupidly disabling ocean tiles. i'm guessing this was thanks to the `FULL_SCREEN_EFFECT` keyword and i didnt test enough at shallow depths. d'oh.

The only note i have is that OnWillRenderObject silently depends on outside state - Camera. current being set, or OceanChunkRenderer.BeginCameraRendering() having been called first to set _currentCamera (would not be the case if hte renderer/tile was disabled). In HDRP this camera variable is barely used, but i checked and it is used in a meaningful way in URP. could we perhaps leave OnWillRenderObject private, and move its contents into a new general function which receives the camera as input, for example:

`internal void BindOceanData(Camera camera)`

does that make sense?

**Comment by moosichu** [comment]
Works for me, will give that a go.

**Comment by moosichu** [comment]
Done :)

**Comment by huwb** [comment]
Sure thing! Happy to make it, I feel bad for misleading you :). But I'm also heading out, so let's just sync later. Will make hdrp release tomorrow I think so no critical rush. Cheers!

**Comment by huwb** [comment]
Merged as suggested!

**Pull request merged**
