### PR TITLE
Remove geometry shader support completely

### LINKED ISSUE #310: Register ocean depth failing
@moosichu as discussed on discord.

Repro: Create a large sphere and assign the Register Ocean Depth script, it won't input its depth to the system so the waves ignore it.

I see the depth cache renders using the GS, but the shader here is OceanDepths.shader which doesnt have GS, but i'm not really clear on what the solution is?

### PR DESCRIPTION
**Pull request by moosichu**
After conversations with @huwb, despite the theoretical benefits of
a reduction in drawcall overhead, the maintenance costs aren't
currently worth it. Especially as many mobile platforms do not support
geometry shaders at all - and they are the ones which are the most
drawcall bound anyway.

Resolves #310.

### CODE REVIEW

**Comment by moosichu** [comment]
It is always nice to have a commit which deletes a lot of code!

**Comment by moosichu** [comment]
This replaces #317

**Comment by cowhunt** [comment]
This is my favourite PR ever. Looks great to me. I ran a quick test with registering a depth input and it worked for me.

**Comment by huwb** [comment]
This is my favourite PR ever. Looks great to me. I ran a quick test with registering a depth input and it worked for me.

**Pull request merged**
