### PR TITLE
Simple first version of dashboard

### PR DESCRIPTION
**Pull request by huwb**
Status: Ready to merge

This is a general purpose window to add dev stuff, but would not be intended to be included in published packages. Hence it is put outside the main crest folder.

So far it has scene loading buttons.

We could add buttons to resave SGs or to do other automation.

Thoughts @daleeidd / @moosichu ?

Thanks!

### CODE REVIEW

**Comment by moosichu** [comment]
Nice one! Only thing I can add at this moment is that we should add an Editor and Runtime asmdef for this dashboard stuff. But looks good otherwise. :)

**Comment by daleeidd** [comment]
Perfect. This will be really handy

**Comment by huwb** [comment]
@moosichu do you think you could add the asmdefs for me? my available time is pockets of around 5min on my phone at the moment and i'm a bit cold when it comes to this stuff

**Comment by huwb** [comment]
Thanks. Assume we're happy with this, merging.

**Pull request merged**
