### PR TITLE
Ocean Debug GUI housekeeping

### PR DESCRIPTION
**Pull request by daleeidd**
TextureArray shader
- Use code style similar to other shaders
- Use unity_ColorSpaceDouble to brighten textures
- Use newer UnityObjectToClipPos
- UV only needs to be float2

OceanDebugGUI
- Make bottom bar full width if sidebar hidden

### CODE REVIEW

**Comment by huwb** [comment]
Wow I hadn't come across unity_ColorSpaceDouble, feel like i should really know about that..

So this should be used even with render textures that are not originating from sRGB images?

**Comment by daleeidd** [comment]
I'm not 100% on the correct usage. I was following along to this [article](https://catlikecoding.com/unity/tutorials/rendering/part-3/). And I thought maybe this is what Unity does for GUI textures by default. The value is similar to what I was already doing (x 4), which I had to do since we aren't using a GUI texture anymore, and they were really dark.

But now that you point it out, I am doubting that I am using it correctly. Maybe I should be looking into UnityUI instead.

**Comment by daleeidd** [comment]
It seems like it is mainly used for detail textures and skyboxes going by the Unity's shaders.

**Comment by huwb** [comment]
Yeah i also ended up at that article. If i understood correctly that change will be doubling the image intensity when rendering in Linear? If so i dont think we want that..

**Comment by daleeidd** [comment]
It does:
```
#define unity_ColorSpaceDouble fixed4(4.59479380, 4.59479380, 4.59479380, 2.0)
```

**Comment by daleeidd** [comment]
This is what it would look like without any change to the intensity:
Dark

It's not too bad, TBH. And more details do come back

**Comment by huwb** [comment]
Yeah.. i think some of the data is already blown out in the viz so I'd vote for not multiplying them up further.

**Comment by daleeidd** [comment]
No worries. I will fix this up shortly

**Comment by daleeidd** [comment]
Done. Thanks for the feedback

**Comment by huwb** [comment]
Nice one! Had an offline thought - could you ping me on discord or mail me: huw.bowles@gmail.com

**Pull request merged**
