### PR TITLE
Fix Terrain "Draw Instanced" not working with Ocean Depth Cache

### LINKED ISSUE #158: Terrain ocean depth - draw instanced
I just did a pull from today to test the changes to project since I last looked.

I noticed that if you use Unity terrain and have "Draw Instanced" enabled 
For some reason it does not get the depth mask correctly, it completely ignores the terrain.

Switch off the "Draw Instanced" and it's all fine.
This is the option in the Terrain settings which arrived with Unity 2018.3

It's something to be aware of, not sure how easy it is to work around as I'm not 100% certain why it's affecting it like this.

### PR DESCRIPTION
**Pull request by daleeidd**
Fixes #158 #371

Based on @huwb's branch: [fix/cache-terrain-depths](https://github.com/crest-ocean/crest/tree/fix/cache-terrain-depths)

Brings over fixes from downstream. Copies depth instead of rendering geometry into ocean depth cache. This didn't work before in 2018 but now works in 2019. Tested on MacOS in build and standalone.

These files are now same as downstream with a few exceptions:
- The copy depth shader use CG instead of HLSL, but they are only a few lines that are different.
- This C# file has a few additional lines which will be added downstream. Allows the depth cache to be used in a prefab

The diff is messy so it is easier to compare these files with the downstream files.

### CODE REVIEW

**Comment by daleeidd** [comment]
Tested on Windows in the editor and standalone and it works.

**Review by huwb — APPROVED** [review]
Looks great. Is there a shader for populating the depth cache that can be removed as well? I can't remember and I don't have my laptop handy so I might be taking rubbish.

**Comment by daleeidd** [comment]
Doesn't appear to be. There is only three depth cache shaders:
OceanDepths (used for register inputs)
OceanDepthsCache (used with register input on the cache quad)
CopyDepthIntoCache (used to blit camera texture to cache texture)

**Comment by daleeidd** [comment]
And thanks. Merging.

**Pull request merged**
